# Generated by Django 5.1.4 on 2025-01-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='passeord',
            new_name='password',
        ),
    ]
